### ISSUE TITLE
USER STORY: create posts

### ISSUE THREAD

**Issue by Julia-cloudname** [Julia-cloudname/marisol#11]
EPIC: #3 

As an **admin** I can **create blog posts,** so I can **manage content**

**Acceptance criteria**
- Admin can add new blog post from admin panel 
- Post form has title, slug, author, content-field with editor panel, image, status and save button
- Admin can see properties of post (status, slug, title, creaded date)
- Admin can filter posts and use search-panel

**Tasks**

- [x] Import Post model
- [x] Install Django summernote
- [x] Add summernote app to requitements.txt
