### ISSUE TITLE
USER STORY: deploy empty site on Heroku

### ISSUE THREAD

**Issue by Julia-cloudname** [Julia-cloudname/marisol#8]
EPIC: #1 

As a **developer** I want to **set up the Django environment** so I can see empty site

**Acceptance criteria**
The empty site works on Heroku 

**Tasks**

- [x] Install Django and supporting libraries
- [x] Create a new blank Django project and App
- [x] Set project to use Cloudinary and PostgreSQL
- [x] Deploy empty site to Heroku
